### ISSUE TITLE
ChromeOS 118 stable supported?

### ISSUE THREAD

**Issue by giaur500** [chromebrew/chromebrew#8919] opened 2023-11-10 17:05 UTC
Crew works just fine on FydeOS/ChromiumOS 114. But now I'm on official Chrome OS - latest stable 118 installed with Brunch and I can't get it working anymore. Some info:
- ChromeOS 118
- developer mode enabled
- no sudo available at all

Sudo is removed completly from ChromeOS, but I am still able to get root acces on Ctrl+Fn terminal, so that's what I did:
- go to Vt2 terminal (Ctrl+F2)
- login as root user - no problems
- run script to install chromebrew as your docs says

And after I run your script, I am getting imnefiate logout, terminal restart and login prompt, without any error messages.

Ant ideas what's wrong?

**Comment by uberhacker** [comment] 2023-11-10 17:17
Try this.  Login to VT-2 as user chronos (no password should be required).  Then run `sudo chown -R chronos /usr/local`.  After this try the install script again.  Hopefully, it will install without an issue.

**Comment by giaur500** [comment] 2023-11-10 17:36
As I mentioned, there's no sudo anymore. But your idea works. I logged to vt2 as root, did chown -R as you said and now I am able to install crew as chronos user even on chrome os terminal (no need to do that in vtx terminals). It seems it works fine

**Comment by satmandu** [comment] 2023-11-11 15:42
`sudo` exists and works (only  in VT-2), if you login as chronos, and you have set the chronos password.

**Comment by Tide-Pods** [comment] 2023-11-12 22:27
you should mark this as solved. I was also having this issue until I saw this post

**Comment by giaur500** [comment] 2023-12-03 20:28
Ok, some more info. Crew acutally works, but in Vt2 terminal only. I am not able to use it after opeining Ctrl+Alt+T terminal + type shell. If i run gui app on VT2 terminal, it will be shown on VT1.

**Comment by uberhacker** [comment] 2023-12-03 20:41
@giaur500: Users are unaware of the need to install in VT2 with the current instructions.

**Comment by giaur500** [comment] 2023-12-03 20:50
Have you read my above post? You can install on vt2, but you are also not able to use it on Ctrl+Alt+T terminal since Chromium 119 update.  You are also forced to use and run any app from VT2 terminal, otherwise you will always get permission denied and sommelier crash due to permission denied:

![image](https://github.com/chromebrew/chromebrew/assets/26817206/9f6a75ed-5072-4c16-a66a-947b7de9cbc9)

**Comment by uberhacker** [comment] 2023-12-04 00:12
> I'm not entirely sure what you did, but it looks like the permisson issue is because the owner of `/usr/local` is root, not chronos.
> 
> If you log into the `VT-2` terminal and run `sudo chown -R 1000:1000 /usr/local`, do things work after that?

This is exactly why we need VT-2 instructions in README.md.  Let me remind you that sudo does not work outside of VT-2 for the newer ChromeOS releases.

**Comment by supechicken** [comment] 2023-12-04 01:12
@giaur500 Regarding the `Permission denied` issue in `crosh`, we have discussed it in our Slack channel before (likely caused by [the `landlock` changes in login_manager](https://chromium.googlesource.com/chromiumos/platform2/+/9e9cc2970439cd7fb3fec5837745d66671c97072)):

> crosh itself should be irrelevant (in  my knowledge root permission is required in order to intercept and block filesystem access in userspace). Here are my current thoughts:
>
> - Should be irrelevant to the kernel (I am using Brunch and haven't updated my kernel for a while)
> - It seems to be about namespace or some isolated things like seccomp (likely can be done with minijail0)
```

**Comment by taroumaru52** [comment] 2023-12-30 09:28
https://chromiumdash.appspot.com/serving-builds?deviceCategory=ChromeOS
You can flash and downgrade to m116
and cgpt to change m116 on kernel B  m119 on kernel A

**Comment by satmandu** [comment] 2023-12-30 10:10
> https://chromiumdash.appspot.com/serving-builds?deviceCategory=ChromeOS
> You can flash and downgrade to m116
> and cgpt to change m116 on kernel B  m119 on kernel A

Could you provide some more detailed instructions for those who would want to try this?

And can we set a boot parameter to adjust this setting in the newer kernels instead of reverting to the older kernel version?

**Comment by DvaMishkiLapa** [comment] 2024-01-09 13:56
> Guys, I'm not sure you understand what I mean. Have tested it on ChromeOS 119? That's how it works now

I'll join the problem. I am using [lenovo duet ct-x636f](https://wiki.postmarketos.org/wiki/Lenovo_IdeaPad_Duet_Chromebook_(google-krane)) on ChromeOS 120. It is impossible to work with Crew packages in VT-2.
- Granting `sudo chown -R 1000:1000 /usr/local` does not solve the problem;
- Granting `sudo chown -R chronos /usr/local` did not solve the problem;

Google seems to be tightening the screws more and more so that the user can't do anything outside of the sandbox.

**Comment by supechicken** [comment] 2024-01-13 05:48
In the latest M122 canary, this issue should be fixed.

For the workaround on older milestones, appending the `lsm=selinux` kernel parameter (to disable the Landlock LSM) fixed the `Permission denied` error for me.

**Comment by satmandu** [comment] 2024-01-13 19:30
@supechicken can we leave a note on the main page readme instructing users in changing the kernel cmdline flags?

**Comment by eudy97** [comment] 2024-01-13 21:39
With 122 still being quite a bit away, here is my current work around from scratch:

Install Chromebrew:

1.  Open VT-2 (CTRL + ALT + Refresh)
2.  Sign in as chronos
3.  Install chromebrew: exec bash --init-file <(curl -Ls git.io/vddgY)
4.  Update source: source ~/.bashrc

Install crew-sudo:

1.  Install supechicken repo: CREW_REPO=https://github.com/supechicken/chromebrew CREW_BRANCH=crew-sudo crew update
2.  Update crew: crew update
3.  Upgrade crew: crew upgrade
4.  Upgrade crew again: crew upgrade
5. Install crew-sudo: crew install crew-sudo
6. Update source again: source ~/.bashrc

Install Gnome terminal and create a permanent alias so you can invoke by just typing "terminal" in CROSH:

1. Install gnome-terminal: crew install gnome-terminal
2. Install nano: crew install nano
3. Edit .bashrc: sudo nano ~/.bashrc
4. Create an alias for gnome-terminal (add this at the bottom of the file): alias terminal="sudo gnome-terminal"
5. CTRL + S to save
6. Exit VT-2 (CTRL + ALT + Back Arrow)

Edit Gnome terminal preferences so it opens as chronos instead of root:

1. Open CROSH (CTRL + ALT + T) 
If it doesn't open, open a browser window first and then press CTRL + ALT + T
2. Ignore all the sommelier errors and either wait or press CTRL + C
3. Type: terminal --preferences
4. Type your password
5. Select "Unanmed" profile
6. Select command
7. Tick "Run a custom command instead of my shell" box
8. add to the custom command field: su chronos
9. Click close and close the gnome-terminal

Now everything you use to do in CROSH before ChromeOS 117 you can do through the Gnome terminal.

Some of the benefits of this method are:

1. Run chromebrew commands through the Gnome terminal instead VT-2
2. Use "terminal" instead of "sudo gnome-terminal" 
3. Use copy and Paste
4. Run GUI apps
5. sudo works now thanks to crew-sudo 

Please provide feedback.

**Comment by satmandu** [comment] 2024-02-10 02:52
M121 fixes this.

**Closed by satmandu** 2024-02-10 02:52 UTC
Labels: upstream 🎢, fix released
