### ISSUE TITLE
🐞 Bug "some sommelier processes failed to start"

### ISSUE THREAD

**Issue by aont** [chromebrew/chromebrew#9750] opened 2024-05-05 00:36 UTC
**Describe the bug**

some sommelier processes failed to start

**To Reproduce**

Environment
ASUS L202S
terra 97.0.4692.77 https://chrome100.dev/board/terra/
brunch_r97_stable_20220121 https://github.com/sebanc/brunch

```
$ brew install sommelier
...
wayland-info: /usr/local/lib64/libc.so.6: version `GLIBC_2.34' not found (required by wayland-info)
wayland-info: /usr/local/lib64/libc.so.6: version `GLIBC_2.34' not found (required by wayland-info)
Sommelier SCALE is set to 1.
SCALE may be manually set in ~/.sommelier.env .
[1]+  Exit 1                  crew install sommelier
some sommelier processes failed to start
```

```
$ readlink -f '/sys/class/drm/renderD129/device/driver'
(no output)
$ readlink -f '/sys/class/drm/renderD128/device/driver'
/sys/bus/pci/drivers/i915
```

**Comment by Zopolis4** [comment] 2024-05-06 00:23
Not sure how you're running anything with `brew install`, but the issue you're facing should have been fixed by #9390.

As per the issue template, please paste the output of `crew sysinfo -v`, as the probable cause of the issue is that you have not updated recently.

**Comment by aont** [comment] 2024-05-06 02:26
@Zopolis4 Thanks.

```
$ crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.47.5`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: d44d89626 `Edge 124.0.2478.67-1 => 124.0.2478.80-1 (#9748) (2 days ago)`

- OS variant: `Chrome OS`
- OS version: `terra-release/R97-14324.62.0`
- OS channel: `stable-channel`

</details>
```

It seems #9390 is already reflected on my crew.
```
$ cat /usr/local/lib/crew/packages/wayland_info.rb 
...
  min_glibc '2.34'
...
```

**Comment by aont** [comment] 2024-05-06 02:46
Additional information (log)
[install_crew.txt](https://github.com/chromebrew/chromebrew/files/15215445/install_crew.txt)
[crew_install_sommelier.txt](https://github.com/chromebrew/chromebrew/files/15215444/crew_install_sommelier.txt)

**Comment by satmandu** [comment] 2024-05-06 12:22
Thanks for the additional info. I think I have tracked down why this was breaking for you.

**Closed** 2024-05-06 14:35 UTC
