### ISSUE TITLE
[crew-launcher] Unable to add firefox

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#6863] opened 2022-03-17 07:19 UTC
```
$ crew-launcher add firefox
crew-launcher server daemon with PID 11976 stopped.
identify identify: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found").
identify identify: Request did not return an image.
convert convert: Unable to load module ("/usr/local/lib64/GraphicsMagick-1.3.35/modules-Q8/coders/png.la: file not found").
/usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `system': Command failed with exit 1: convert (RuntimeError)
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:14:in `convert_img'
        from /usr/local/share/crew-launcher/lib/icon_finder.rb:39:in `find'
        from /usr/local/bin/crew-launcher:73:in `CreateProfile'
        from /usr/local/bin/crew-launcher:107:in `InstallPWA'
        from /usr/local/bin/crew-launcher:216:in `<main>'
```

**Comment by satmandu** [comment] 2022-03-17 13:15
Add imagemagick as a dep!

**Comment by supechicken** [comment] 2022-03-17 13:59
> Add imagemagick as a dep!

`crew-launcher` uses `graphicsmagick` instead of `imagemagick` for smaller installation size, but no idea about the missing library error😅

**Comment by saltedcoffii** [comment] 2022-10-19 20:50
closing as duplicate of #6314

**Closed by saltedcoffii** 2022-10-19 20:50 UTC
Labels: bug 🐛, x86_64
