### ISSUE TITLE
[icu4c] llvm-strip error

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#4986] opened 2021-01-24 14:46 UTC
```
icu4c: ICU is a mature, widely used set of C/C++ and Java libraries providing Unicode and Globalization support for software applications.
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Removing since upgrade or reinstall...
Icu4c removed!
Performing pre-install...
Performing install...
llvm-strip: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory
llvm-strip: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory
Performing post-install...
Icu4c installed!
```

**Comment by satmandu** [comment] 2021-01-24 19:19
libicui18n.so.68 is in icu4c... so removing icu4c will keep that from being available until icu4c is reinstalled.

**Comment by satmandu** [comment] 2021-01-24 19:34
```
chronos@cheekon-i686 /usr/local/lib/crew/packages $ crew whatprovides libicui18n.so.68
icu4c: /usr/local/lib/libicui18n.so.68
icu4c: /usr/local/lib/libicui18n.so.68.2

Total found: 2
chronos@cheekon-i686 /usr/local/lib/crew/packages $ 
```

**Comment by uberhacker** [comment] 2021-01-25 00:53
I still get the error after `crew reinstall icu4c`.

**Comment by kjperkin** [comment] 2021-01-25 08:29
The problem is that install_package removes the current package before the new files are ready to be moved into place. A naive solution would be to strip the binaries, then remove the package. However, I worry that there may be pre-install code that assumes that the previous version was removed by the time it is called...

**Comment by uberhacker** [comment] 2021-01-25 15:37
@kjperkin: Yes, I think the issue is `llvm-strip` should not be called until AFTER the files from the `icu4c` package are installed.

**Comment by kjperkin** [comment] 2021-01-25 17:36
I think that would be ideal, but harder than doing it immediately before removing the previous version. The issue is that `strip_find_files` seems to be written with the assumption that it will be called for what I'll refer to as the "staging" directory (/usr/local/tmp/crew/<package.tar.xz>.dir). We wouldn't want to llvm-strip the entirety of /usr/local, especially not for every install.

In my perfect world, we'd implement all that `find` stuff and identifying ELF or ar files in pure ruby. Then we'd call llvm-strip ourselves with `system`.

**Comment by satmandu** [comment] 2021-01-25 17:43
@uberhacker Are you still getting the error despite icu4c being installed?

**Comment by uberhacker** [comment] 2021-01-26 20:01
@satmandu: I get the error with `crew reinstall icu4c`.  Try and see for yourself.

**Comment by satmandu** [comment] 2021-01-26 20:13
@uberhacker That's not surprising. Reinstall does an uninstall and then an install... the uninstall removes the library... and maybe an ldconfig isn't done until after llvm-strip is run on the package, so llvm-strip will complain about the library being missing...

The deps for llvm-strip include icu4c, libffi, and libedit.

**Comment by uberhacker** [comment] 2021-01-26 22:42
I think there is a fundamental problem here.  Why are we even attempting to execute llvm-strip if the files are missing?

**Comment by kjperkin** [comment] 2021-01-27 01:46
I created a naive fix for this in defe9a8, but as I noted above, I'm not sure it's the right approach since it interleaves the steps in a different way...

**Comment by satmandu** [comment] 2021-01-27 18:11
@uberhacker The dependencies for llvm-strip are installed in install.sh before llvm-strip is run on a fresh install.

How would you suggest one deal with running a script which is uninstalling and reinstalling a dependency of the said script? It's a complicated problem.  You could have llvm-strip not run if a packages being processed is one of the dependencies for llvm-strip, or you could just have llvm-strip throw an error for those packages.

It's a question of how complex one would like the logic to be.

**Comment by Zopolis4** [comment] 2024-06-03 23:18
We strip at build time as of #5699.

![image](https://github.com/chromebrew/chromebrew/assets/64618338/b6cd1a98-460f-428e-9ca3-ad6553de0aae)

**Closed by Zopolis4** 2024-06-03 23:18 UTC
Labels: aarch64, x86_64, armv7l, i686
